 # Needs 
       - if: 
         jobs:
           setup:
            run-on: ubuntu-latest 
             steps: 
               - run: ./setup_server.sh
           build:
             needs: setup
             runs-on: ubuntu-latest 
             - steps: ./build_server.sh
           test:
             needs: setup 
             runs-on: ubuntu-latest
               - steps:
             - run:./build_server.sh
